export const allTimezones = [
  { value: "#|0:00", label: "None" },
  { value: "aoe|-12:00", label: "(GMT -12) Int. Date Line" },
  { value: "sst|-11:00", label: "(GMT -11) SST: Samoa" },
  { value: "hast|-10:00", label: "(GMT -10) HAST: Hawaii" },
  { value: "hadt|-9:00", label: "(GMT -9) HADT: Hawaii (Daylight)" },
  { value: "akst|-9:00", label: "(GMT -9) AKST: Alaska" },
  { value: "akdt|-8:00", label: "(GMT -8) AKDT: Alaska (Daylight)" },
  { value: "pst|-8:00", label: "(GMT -8) PST: Pacific Standard Time" },
  { value: "pdt|-7:00", label: "(GMT -7) PDT: Pacific Daylight Time" },
  { value: "mst|-7:00", label: "(GMT -7) MST: Mountain Standard Time" },
  { value: "mdt|-6:00", label: "(GMT -6) MDT: Mountain Daylight Time" },
  { value: "cst|-6:00", label: "(GMT -6) CST: Central Standard Time" },
  { value: "cdt|-5:00", label: "(GMT -5) CDT: Central Daylight Time" },
  { value: "est|-5:00", label: "(GMT -5) EST: Eastern Standard Time" },
  { value: "pet|-5:00", label: "(GMT -5) PET: Peru" },
  { value: "act|-5:00", label: "(GMT -5) ACT: Acre, Brazil" },
  { value: "vet|-4:30", label: "(GMT -4:30) VET: Venezuela" },
  { value: "edt|-4:00", label: "(GMT -4) EDT: Eastern Daylight Time" },
  { value: "ast|-4:00", label: "(GMT -4) AST: Atlantic Standard Time" },
  { value: "nst|-3:30", label: "(GMT -3:30) NST: Newfoundland Time" },
  { value: "adt|-3:00", label: "(GMT -3) ADT: Atlantic Daylight Time" },
  { value: "art|-3:00", label: "(GMT -3) ART: Argentina" },
  { value: "brt|-3:00", label: "(GMT -3) BRT: Brazil" },
  { value: "wgt|-3:00", label: "(GMT -3) WGT: West Greenland" },
  {
    value: "ndt|-2:30",
    label: "(GMT -2:30) NST: Newfoundland Daylight Time"
  },
  {
    value: "wgst|-2:00",
    label: "(GMT -2) WGST: West Greenland Summer Time"
  },
  { value: "brst|-2:00", label: "(GMT -2) BRST: Brazil Summer Time" },
  { value: "egt|-1:00", label: "(GMT -1) EGT: East Greenland" },
  { value: "azot|-1:00", label: "(GMT -1) AZOT: Azores" },
  { value: "azost|0:00", label: "(GMT +0) AZOST: Azores Summer" },
  { value: "egst|0:00", label: "(GMT +0) EGST: East Greenland Summer" },
  { value: "gmt|0:00", label: "GMT: Greenwich Mean Time" },
  { value: "wet|0:00", label: "(GMT +0) WET: Western European Time" },
  { value: "bst|1:00", label: "(GMT +1) BST: British Summer Time" },
  { value: "cet|1:00", label: "(GMT +1) CET: Central European Time" },
  { value: "ist|1:00", label: "(GMT +1) IST: Irish Standard Time" },
  {
    value: "cest|2:00",
    label: "(GMT +2) CEST: Central European Summer Time"
  },
  { value: "cat|2:00", label: "(GMT +2) CAT: Central Africa Time" },
  { value: "eet|2:00", label: "(GMT +2) EET: Eastern European Time" },
  {
    value: "sast|2:00",
    label: "(GMT +2) SAST: South Africa Standard Time"
  },
  { value: "eat|3:00", label: "(GMT +3) EAT: East Africa Time" },
  {
    value: "eest|3:00",
    label: "(GMT +3) EEST: Eastern European Summer Time"
  },
  { value: "msk|3:00", label: "(GMT +3) MSK: Moscow Standard Time" },
  { value: "irst|3:30", label: "(GMT +3:30) IRST: Iran Standard Time" },
  { value: "gst|4:00", label: "(GMT +4) GST: Gulf Standard Time" },
  { value: "mdk|4:00", label: "(GMT +4) MDK: Moscow Daylight Time" },
  { value: "irdt|4:30", label: "(GMT +4:30) IRDT: Iran Daylight Time" },
  { value: "mvt|5:00", label: "(GMT +5) MVT: Maldives Time" },
  { value: "ist|5:30", label: "(GMT +5:30) IST: India Standard Time" },
  { value: "bst|6:00", label: "(GMT +6) BST: Bangladesh Standard Time" },
  { value: "mmt|6:30", label: "(GMT +6:30) MMT: Myanmar Time" },
  { value: "wib|7:00", label: "(GMT +7) WIB: Western Indonesian Time" },
  { value: "wita|8:00", label: "(GMT +8) WITA: Central Indonesian Time" },
  {
    value: "awst|8:00",
    label: "(GMT +8) AWST: Australia Western Standard Time"
  },
  { value: "cst|8:00", label: "(GMT +8) CST: China Standard Time" },
  { value: "hkt|8:00", label: "(GMT +8) HKT: Hong Kong Time" },
  { value: "pyt|8:30", label: "(GMT +8:30) PYT: Pyongyang Time" },
  { value: "wit|9:00", label: "(GMT +9) WIT: Eastern Indonesian Time" },
  {
    value: "awdt|9:00",
    label: "(GMT +9) AWDT: Australia Western Daylight Time"
  },
  { value: "jst|9:00", label: "(GMT +9) JST: Japan Standard Time" },
  { value: "kst|9:00", label: "(GMT +9) KST: Korea Standard Time" },
  {
    value: "acst|9:30",
    label: "(GMT +9:30) ACST: Australia Central Standard Time"
  },
  {
    value: "aest|10:00",
    label: "(GMT +10) AEST: Australia Eastern Standard Time"
  },
  { value: "pgt|10:00", label: "(GMT +10) PGT: Papua New Guinea Time" },
  {
    value: "acdt|10:30",
    label: "(GMT +10:30) ACDT: Australia Central Daylight Time"
  },
  {
    value: "aedt|11:00",
    label: "(GMT +11) AEDT: Australia Eastern Daylight Time"
  },
  { value: "fjt|12:00", label: "(GMT +12) FJT: Fiji Time" },
  {
    value: "nzst|12:00",
    label: "(GMT +12) NZST: New Zealand Standard Time"
  },
  { value: "fjst|13:00", label: "(GMT +13) FJST: Fiji Summer Time" },
  {
    value: "nzdt|13:00",
    label: "(GMT +13) NZDT: New Zealand Daylight Time"
  },
  { value: "wst|14:00", label: "(GMT +14) WST: Western Samoa Time" }
];

export const defaultState = {
  leadingZero: true,
  bluetoothDisconnect: true,
  update: true,
  timezones: "#|0:00",
  slotA: "1",
  slotB: "2",
  slotC: "3",
  slotD: "4",
  sleepSlotA: "1",
  sleepSlotB: "2",
  sleepSlotC: "6",
  sleepSlotD: "7",
  locale: "0",
  dateFormat: "0",
  textAlign: "2",
  fontType: "6",
  enableAdvanced: false,
  weatherProvider: "2",
  useCelsius: false,
  overrideLocation: "",
  showSleep: false,
  weatherKey: "",
  forecastKey: "",
  speedUnit: "0",
  showDebug: false,
  quickview: true,
  dateSeparator: "1",
  muteOnQuiet: false,
  showTap: false,
  tapTime: "7",
  tapSlotA: "15",
  tapSlotB: "14",
  tapSlotC: "5",
  tapSlotD: "13",
  weatherTime: "30",
  heartLow: "0",
  heartHigh: "0",
  showWrist: false,
  wristSlotA: "11",
  wristSlotB: "12",
  wristSlotC: "8",
  wristSlotD: "16",
  masterKeyEmail: "",
  masterKeyPin: "",
  slotE: "18",
  slotF: "17",
  sleepSlotE: "18",
  sleepSlotF: "17",
  tapSlotE: "18",
  tapSlotF: "17",
  wristSlotE: "18",
  wristSlotF: "17",
  openWeatherKey: "",
  presets: {}
};

export const defaultColors = {
  bgColor: "#000000",
  hoursColor: "#FFFFFF",
  dateColor: "#FFFFFF",
  altHoursColor: "#FFFFFF",
  batteryColor: "#FFFFFF",
  batteryLowColor: "#FFFFFF",
  bluetoothColor: "#FFFFFF",
  updateColor: "#FFFFFF",
  weatherColor: "#FFFFFF",
  tempColor: "#FFFFFF",
  minColor: "#FFFFFF",
  maxColor: "#FFFFFF",
  stepsColor: "#FFFFFF",
  stepsBehindColor: "#FFFFFF",
  distColor: "#FFFFFF",
  distBehindColor: "#FFFFFF",
  calColor: "#FFFFFF",
  calBehindColor: "#FFFFFF",
  sleepColor: "#FFFFFF",
  sleepBehindColor: "#FFFFFF",
  deepColor: "#FFFFFF",
  deepBehindColor: "#FFFFFF",
  windDirColor: "#FFFFFF",
  windSpeedColor: "#FFFFFF",
  sunriseColor: "#FFFFFF",
  sunsetColor: "#FFFFFF",
  activeColor: "#FFFFFF",
  activeBehindColor: "#FFFFFF",
  heartColor: "#FFFFFF",
  heartColorOff: "#FFFFFF",
  compassColor: "#FFFFFF",
  secondsColor: "#FFFFFF"
};
