#ifndef __TIMEBOXED_KEYS_
#define __TIMEBOXED_KEYS_

#define KEY_TEMP 0
#define KEY_MAX 1
#define KEY_MIN 2
#define KEY_WEATHER 3
#define KEY_ENABLEHEALTH 4
#define KEY_USEKM 5
#define KEY_SHOWSLEEP 6
#define KEY_ENABLEWEATHER 7
#define KEY_WEATHERKEY 8
#define KEY_USECELSIUS 9
#define KEY_TIMEZONES 10
#define KEY_BGCOLOR 11
#define KEY_HOURSCOLOR 12
#define KEY_ENABLEADVANCED 13
#define KEY_DATECOLOR 14
#define KEY_ALTHOURSCOLOR 15
#define KEY_BATTERYCOLOR 16
#define KEY_BATTERYLOWCOLOR 17
#define KEY_WEATHERCOLOR 18
#define KEY_TEMPCOLOR 19
#define KEY_MINCOLOR 20
#define KEY_MAXCOLOR 21
#define KEY_STEPSCOLOR 22
#define KEY_DISTCOLOR 23
#define KEY_TIMEZONESCODE 24
#define KEY_TIMEZONESMINUTES 25
#define KEY_FONTTYPE 26
#define KEY_STEPS 27
#define KEY_DIST 28
#define KEY_BLUETOOTHDISCONNECT 29
#define KEY_BLUETOOTHCOLOR 30
#define KEY_OVERRIDELOCATION 31
#define KEY_ERROR 32
#define KEY_UPDATE 33
#define KEY_UPDATECOLOR 34
#define KEY_HASUPDATE 35
#define KEY_LOCALE 36
#define KEY_DATEFORMAT 37

#define BLOCKO_FONT 0
#define BLOCKO_BIG_FONT 1
#define SYSTEM_FONT 2
#define ARCHIVO_FONT 3

#define LC_ENGLISH 0
#define LC_PORTUGUESE 1
#define LC_FRENCH 2
#define LC_GERMAN 3
#define LC_SPANISH 4
#define LC_ITALIAN 5
#define LC_DUTCH 6
#define LC_DANISH 7
#define LC_TURKISH 8
#define LC_CZECH 9
#define LC_POLISH 10
#define LC_SWEDISH 11
#define LC_FINNISH 12

#define FORMAT_WMD 0
#define FORMAT_WDM 1

#endif
